"""
VortexRAG — GitHub PR Review Agent (Phase 5)
Intercepts GitHub PR webhooks, reads the diff, uses the LangGraph agent to check for architectural/logical issues against the codebase, and posts an automated review comment.
"""
import logging
from github import Github, Auth
from app.core.config import settings
from app.services.rag_agent import RAGAgent

logger = logging.getLogger("vortex")

class PRReviewer:
    """
    Automated Pull Request reviewer that uses the codebase context (via RAGAgent)
    to provide highly contextual architectural and logical reviews.
    """
    def __init__(self):
        # We assume standard Personal Access Token for the MVP, 
        # though a true GitHub App uses private keys.
        self.auth = Auth.Token(settings.GITHUB_WEBHOOK_SECRET) if settings.GITHUB_WEBHOOK_SECRET else None
        self.gh = Github(auth=self.auth) if self.auth else Github()
        self.agent = RAGAgent()

    async def review_pr(self, repo_full_name: str, pr_number: int, repo_id: str) -> dict:
        """
        Fetches the PR diff, analyzes it using the RAG Agent, and posts a review comment.
        """
        logger.info(f"👀 [PR Reviewer] Analyzing PR #{pr_number} in {repo_full_name} (repo_id: {repo_id})")
        
        try:
            repo = self.gh.get_repo(repo_full_name)
            pr = repo.get_pull(pr_number)
            
            # Get the diff (files changed)
            files = pr.get_files()
            diff_text = ""
            for file in files:
                diff_text += f"\nFile: {file.filename}\nStatus: {file.status}\nPatch:\n{file.patch}\n"
            
            if not diff_text.strip():
                logger.info("PR has no file changes to review.")
                return {"status": "skipped", "message": "No file changes"}

            # Construct the prompt for the RAG Agent
            prompt = (
                f"Review the following Pull Request diff for architectural and logical issues. "
                f"Use the indexed codebase to check if these changes break any existing dependencies or conventions. "
                f"Here is the diff:\n\n{diff_text}"
            )
            
            logger.info("🤖 [PR Reviewer] Querying RAG Agent for architectural review...")
            # Query the LangGraph Agent
            agent_result = await self.agent.run(prompt, repo_id)
            review_comment = agent_result["answer"]
            
            # Format the output
            final_comment = (
                "## 🌀 VortexRAG Automated Architectural Review\n\n"
                f"{review_comment}\n\n"
                "---\n"
                "*This review was generated by analyzing your changes against the `vortex-rag` vector/graph index.*"
            )
            
            # Post comment to GitHub (Mocked if no auth token is provided)
            if self.auth:
                pr.create_issue_comment(final_comment)
                logger.info("✅ [PR Reviewer] Review posted to GitHub!")
                return {"status": "success", "message": "Review posted to GitHub.", "comment": final_comment}
            else:
                logger.info("⚠️ [PR Reviewer] GITHUB_WEBHOOK_SECRET not set. Skipping actual post.")
                return {"status": "success_mocked", "message": "Review generated but not posted (no auth token).", "comment": final_comment}

        except Exception as e:
            logger.error(f"❌ [PR Reviewer] Failed to review PR: {e}")
            raise
